export type BoardSpaceKind =
  | "start"
  | "lesson"
  | "game"
  | "challenge"
  | "reward"
  | "gate"
  | "finish";

export type BoardSpace = {
  index: number;
  week: 1 | 2 | 3 | 4;
  kind: BoardSpaceKind;
  title: string;
  shortLabel: string;
  instruction: string;
  href?: string;
  missionId?: string;
  requiredForUnlock?: boolean;
  rewardXp?: number;
  icon: string;
};

export const WEEK_BOARD_META = {
  1: {
    title: "Daily Ledger",
    subtitle: "What, why, double-entry + sales tax",
    color: "#2d7057",
    softColor: "#dceee6",
    icon: "📒",
  },
  2: {
    title: "Account Sorter",
    subtitle: "Trial Balance + account types",
    color: "#7c3aed",
    softColor: "#ede9fe",
    icon: "🗂️",
  },
  3: {
    title: "Reports Room",
    subtitle: "P&L + Balance Sheet → decisions",
    color: "#2563eb",
    softColor: "#dbeafe",
    icon: "📊",
  },
  4: {
    title: "Year-End Boss",
    subtitle: "Year-end journals + accountant handoff",
    color: "#c2410c",
    softColor: "#ffedd5",
    icon: "⚔️",
  },
} as const;

export const BOARD_SPACES: BoardSpace[] = [
  {
    index: 0,
    week: 1,
    kind: "start",
    title: "Open the Books",
    shortLabel: "Start",
    instruction: "Roll to begin your bookkeeping journey.",
    icon: "🚩",
    rewardXp: 25,
  },
  {
    index: 1,
    week: 1,
    kind: "lesson",
    title: "What & Why",
    shortLabel: "What + Why",
    instruction: "Learn what bookkeeping records and why clean books matter.",
    href: "/lessons/lesson-why-bookkeeping",
    missionId: "w1-what-why",
    requiredForUnlock: true,
    icon: "💡",
  },
  {
    index: 2,
    week: 1,
    kind: "game",
    title: "Category Dash",
    shortLabel: "Sort it",
    instruction: "Put everyday spending into the same clear bucket every time.",
    href: "/games/category-blitz?week=1",
    missionId: "w1-category-game",
    icon: "🗂️",
  },
  {
    index: 3,
    week: 1,
    kind: "lesson",
    title: "Two-Sided Trail",
    shortLabel: "Double-entry",
    instruction: "See both sides of a transaction and split sales tax.",
    href: "/lessons/lesson-double-entry",
    missionId: "w1-double-entry",
    requiredForUnlock: true,
    icon: "↔️",
  },
  {
    index: 4,
    week: 1,
    kind: "game",
    title: "Tax Taxi",
    shortLabel: "GST game",
    instruction: "Balance taxi and Home Depot-style entries.",
    href: "/games/balance-entry?week=1",
    missionId: "w1-tax-game",
    icon: "🚕",
  },
  {
    index: 5,
    week: 1,
    kind: "challenge",
    title: "Daily Ledger Gate",
    shortLabel: "Week 1 gate",
    instruction: "Complete the double-entry challenge to open Week 2.",
    href: "/challenges/challenge-double-entry-duel",
    missionId: "w1-gate",
    requiredForUnlock: true,
    icon: "⭐",
    rewardXp: 150,
  },
  {
    index: 6,
    week: 2,
    kind: "gate",
    title: "Account Sorter Opens",
    shortLabel: "Week 2",
    instruction: "Week 2 is open. Assets and liabilities await!",
    icon: "🔓",
    rewardXp: 50,
  },
  {
    index: 7,
    week: 2,
    kind: "lesson",
    title: "Know the Buckets",
    shortLabel: "Account types",
    instruction: "Learn current/fixed assets and current/long-term liabilities.",
    href: "/lessons/lesson-account-types",
    missionId: "w2-account-types",
    requiredForUnlock: true,
    icon: "🧺",
  },
  {
    index: 8,
    week: 2,
    kind: "game",
    title: "Cash Now or Later?",
    shortLabel: "Cash timing",
    instruction: "Spot immediate funds versus receivables, payables, and cards.",
    href: "/games/cash-flow-snap?week=2",
    missionId: "w2-cash-timing",
    icon: "⏱️",
  },
  {
    index: 9,
    week: 2,
    kind: "challenge",
    title: "Account Sorter",
    shortLabel: "Sorter",
    instruction: "Sort every account into its precise Week 2 bucket.",
    href: "/challenges/challenge-sort-accounts",
    missionId: "w2-sorter",
    requiredForUnlock: true,
    icon: "🎯",
  },
  {
    index: 10,
    week: 2,
    kind: "lesson",
    title: "Month-End Check",
    shortLabel: "Trial Balance",
    instruction: "See daily entries compile into a Trial Balance.",
    href: "/lessons/lesson-trial-balance",
    missionId: "w2-trial-balance",
    icon: "🧾",
  },
  {
    index: 11,
    week: 2,
    kind: "game",
    title: "Balance the Books",
    shortLabel: "Week 2 gate",
    instruction: "Keep debits equal to credits — your Week 2 gate star for the board.",
    href: "/games/balance-entry?week=2",
    missionId: "w2-gate",
    requiredForUnlock: true,
    icon: "⚖️",
    rewardXp: 175,
  },
  {
    index: 12,
    week: 3,
    kind: "gate",
    title: "Reports Room Opens",
    shortLabel: "Week 3",
    instruction: "Your balanced books can now become useful reports.",
    icon: "🔓",
    rewardXp: 50,
  },
  {
    index: 13,
    week: 3,
    kind: "lesson",
    title: "Profit & Loss Path",
    shortLabel: "Profit & Loss",
    instruction: "Follow revenue to gross profit, expenses, and net income on the Profit & Loss report.",
    href: "/lessons/lesson-profit-loss",
    missionId: "w3-profit-loss",
    requiredForUnlock: true,
    icon: "📈",
  },
  {
    index: 14,
    week: 3,
    kind: "game",
    title: "Statement Split",
    shortLabel: "P&L or BS?",
    instruction: "Send each Trial Balance account to the right statement.",
    href: "/games/statement-sorter",
    missionId: "w3-statement-sorter",
    icon: "🪄",
  },
  {
    index: 15,
    week: 3,
    kind: "lesson",
    title: "Balance Sheet Bridge",
    shortLabel: "Assets = L + E",
    instruction: "Check that Assets = Liabilities + Equity, then turn report insights into decisions.",
    href: "/lessons/lesson-balance-sheet",
    missionId: "w3-balance-sheet",
    requiredForUnlock: true,
    icon: "🌉",
  },
  {
    index: 16,
    week: 3,
    kind: "game",
    title: "Equation Hero",
    shortLabel: "Equation",
    instruction: "Prove that Assets = Liabilities + Equity.",
    href: "/games/equation-hero",
    missionId: "w3-equation",
    icon: "🧮",
  },
  {
    index: 17,
    week: 3,
    kind: "challenge",
    title: "Insight Detective",
    shortLabel: "Week 3 gate",
    instruction: "Turn report clues into a smart owner decision.",
    href: "/challenges/challenge-insight-detective",
    missionId: "w3-gate",
    requiredForUnlock: true,
    icon: "🕵️",
    rewardXp: 200,
  },
  {
    index: 18,
    week: 4,
    kind: "gate",
    title: "Year-End Opens",
    shortLabel: "Week 4",
    instruction: "The final world is open. Prepare the year-end journals.",
    icon: "🔓",
    rewardXp: 75,
  },
  {
    index: 19,
    week: 4,
    kind: "lesson",
    title: "Three Journals",
    shortLabel: "Year-end lesson",
    instruction: "Learn depreciation, home office, and mileage journals.",
    href: "/lessons/lesson-depreciation",
    missionId: "w4-journals",
    requiredForUnlock: true,
    icon: "📚",
  },
  {
    index: 20,
    week: 4,
    kind: "game",
    title: "Year-End Prep",
    shortLabel: "Prep game",
    instruction: "Practice $14,500, $3,585, and $15,600 adjustments.",
    href: "/games/year-end-prep",
    missionId: "w4-prep",
    icon: "🎯",
  },
  {
    index: 21,
    week: 4,
    kind: "challenge",
    title: "Boss Fight",
    shortLabel: "Post journals",
    instruction: "Calculate and post all three adjusting entries.",
    href: "/challenges/challenge-year-end-boss",
    missionId: "w4-boss",
    requiredForUnlock: true,
    icon: "⚔️",
    rewardXp: 300,
  },
  {
    index: 22,
    week: 4,
    kind: "lesson",
    title: "Accountant Handoff",
    shortLabel: "Handoff",
    instruction: "Package clean reports and supporting schedules.",
    href: "/lessons/lesson-handoff",
    missionId: "w4-handoff",
    requiredForUnlock: true,
    icon: "📦",
  },
  {
    index: 23,
    week: 4,
    kind: "finish",
    title: "Books Balanced!",
    shortLabel: "Victory",
    instruction: "You completed the course and won the Ledger Quest!",
    href: "/certificate",
    icon: "🏆",
    rewardXp: 500,
  },
];

export const REQUIRED_MISSIONS_BY_WEEK: Record<1 | 2 | 3 | 4, string[]> = {
  1: ["w1-what-why", "w1-double-entry", "w1-gate"],
  2: ["w2-account-types", "w2-sorter", "w2-gate"],
  3: ["w3-profit-loss", "w3-balance-sheet", "w3-gate"],
  4: ["w4-journals", "w4-boss", "w4-handoff"],
};

export function getBoardSpace(index: number): BoardSpace {
  return BOARD_SPACES[Math.max(0, Math.min(index, BOARD_SPACES.length - 1))];
}
